In [7]:
import numpy as np
list1=[1123,342,23,234]
array1=np.array(list1 , dtype=float)
print(array1)
np.sort(array1)


[1123.  342.   23.  234.]


array([  23.,  234.,  342., 1123.])

In [2]:
import numpy as np
list1=[[1,2,3],[2,3,4],[4,5,6]]
arr1=np.array(list1)
print(arr1)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [26]:
import numpy as np
arr=np.arange(11,17).reshape(3,2)
print(arr.dtype)

int32


In [24]:
import numpy as np
arr=np.ones((3,3))     #shape 3,3 is given.
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
import numpy as np
arr1=np.ones(4)
print(arr1.ndim)

1
